avoid compiler warnings C4996 with define _CRT_NONSTDC_NO_WARNINGS, see https://msdn.microsoft.com/de-de/library/ttcz0bys.aspx e.g.
zlib\gzlib.c(245): error C4996: 'open': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _open. See online help for details. [C:\projects\npppluginmanager\submodule\zlibstat.vcxproj]